project/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import Index
from formularios.views import ContactoCrear

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index, name='home'),
    path('contacto/', ContactoCrear.as_view(), name='contacto'),
    path('trabajos/', include('trabajos.urls')),
]

trabajos/urls.py
from django.urls import path
from trabajos.views import Mensura, EstadoParcelario, Relevamiento, Amojonamiento, Replanteo, PropiedadHorizontal, Unificacion, Loteo, Usucapion, BarrioCerradoClub

urlpatterns = [
    path('mensura/', Mensura, name='mensura'),
    path('estado-parcelario/', EstadoParcelario, name='estado-parcelario'),
    path('relevamiento/', Relevamiento, name='relevamiento'),
    path('amojonamiento/', Amojonamiento, name='amojonamiento'),
    path('replanteo/', Replanteo, name='replanteo'),
    path('propiedad-horizontal/', PropiedadHorizontal, name='propiedad-horizontal'),
    path('unificacion/', Unificacion, name='unificacion'),
    path('loteo/', Loteo, name='loteo'),
    path('usucapion/', Usucapion, name='usucapion'),
    path('barrio-cerrado-club-campo/', BarrioCerradoClub, name='barrio-cerrado-club'),
]

formularios/models.py
from django.db import models

contacto_servicio = [
    (1, 'Mensura'),
    (2, 'Estado parcelario'),
    (3, 'Relevamiento'),
    (4, 'Amojonamiento'),
    (5, 'Replanteo'),
    (6, 'Subdivision en Propiedad horizontal'),
    (7, 'Unificación'),
    (8, 'Loteo'),
    (9, 'Plano de usucapión'),
    (10, 'Barrio cerrado o club de campo'),
    (11, "Otro")
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=30)
    servicio = models.IntegerField(null=False, blank=False, choices=contacto_servicio)
    localidad = models.CharField(max_length=30)
    correo = models.EmailField(max_length=50)
    numero_telefono = models.CharField(max_length=10)
    mensaje = models.TextField(max_length=2000)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ID: {self.id} | Nombre: {self.nombre} | Trabajo: {self.servicio} |  Fecha: {self.fecha}"

principal/models.py
from django.db import models

trabajos/models.py
from django.db import models

# Create your models here.

formularios/forms.py
from django.forms import ModelForm
from formularios.models import Contacto

class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = ('nombre', 'servicio', 'localidad', 'correo', 'telefono', 'mensaje')

formularios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from formularios.models import Contacto
from django.urls import reverse_lazy

class ContactoCrear(CreateView):
    model = Contacto
    success_url = reverse_lazy("home")
    fields = ['nombre', 'servicio', 'localidad', 'correo', 'numero_telefono', 'mensaje']

principal/views.py
from django.shortcuts import render

def Index(request):
    return render(request, 'principal/index.html')

trabajos/views.py
from django.shortcuts import render

def Mensura(request):
    return render(request, 'trabajos/mensura.html')

def EstadoParcelario(request):
    return render(request, 'trabajos/estado_parcelario.html')

def Relevamiento(request):
    return render(request, 'trabajos/relevamiento.html')

def Amojonamiento(request):
    return render(request, 'trabajos/amojonamiento.html')

def Replanteo(request):
    return render(request, 'trabajos/replanteo.html')

def PropiedadHorizontal(request):
    return render(request, 'trabajos/propiedad_horizontal.html')

def Unificacion(request):
    return render(request, 'trabajos/unificacion.html')

def Loteo(request):
    return render(request, 'trabajos/loteo.html')

def Usucapion(request):
    return render(request, 'trabajos/usucapion.html')

def BarrioCerradoClub(request):
    return render(request, 'trabajos/barrio_cerrado_club.html')

formularios/templates/formularios/contacto_form.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Main Content-->
        <main class="mb-4">
            <header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
                <div class="container px-4 px-lg-5 text-center">
                    <h1>Contacto</h1>
                </div>
            </header>
                <div class="container text-center">
                    <h3>Complete el formulario para que nos comuniquemos</h3>
                </div>
            <!-- Divider-->
            <hr class="my-4" />
            <div class="container px-2 px-lg-10">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-7">
                    <div class="col-md-10 col-lg-10 col-xl-10">
                        <div class="my-5">
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" form  enctype='multipart/form-data' method="post">
                                {% csrf_token %}
                                <div class="form-floating">
                                <p>
                                    <label for="id_nombre">Nombre</label>
                                        <input type="text" name="nombre" class="form-control" maxlength="20" placeholder="Ingrese su nombre..." autofocus id="id_nombre" required>
                                </p>
                                <p>
                                    <label for="id_servicio">Servicio requerido</label><br>
                                    <select name="servicio" id="id_servicio" required>
                                        <option value="" selected="">-SELECCIONAR-</option>
                                        <option value="1">Mensura</option>
                                        <option value="2">Estado parcelario</option>
                                        <option value="3">Relevamiento</option>
                                        <option value="4">Amojonamiento</option>
                                        <option value="5">Replanteo</option>
                                        <option value="6">Subdivision en Propiedad horizontal</option>
                                        <option value="7">Unificación</option>
                                        <option value="8">Loteo</option>
                                        <option value="9">Plano de usucapión</option>
                                        <option value="10">Barrio cerrado o club de campo</option>
                                        <option value="11">Otro</option>
                                      </select>
                                </p>
                                <p>
                                    <label for="id_localidad">Localidad</label>
                                        <input type="text" name="localidad" class="form-control" maxlength="20" placeholder="Ingrese su localidad..." id="id_localidad" required>
                                </p>
                                <p>
                                    <label for="id_correo">Correo</label>
                                    <input type="email" name="correo" class="form-control" placeholder="Ingrese su correo..." data-sb-validations="required,email" id="id_correo" required>
                                </p>
                                <p>
                                <label for="id_numero_telefono">Número de Teléfono</label>
                                <input type="tel" name="numero_telefono" class="form-control" placeholder="Ingrese su número de teléfono..." id="id_numero_telefono" required>
                                </p>
                                <p>
                                <label for="id_mensaje">Mensaje</label>
                                <textarea type="text" name="mensaje" maxlength="2000" class="form-control" placeholder="Ingrese su mensaje..." id="id_mensaje"></textarea>
                                </p>
                            </div>
                                <!-- Submit Button-->
                                <input class="btn btn-outline-dark flex-shrink-0" type="submit" value="Enviar">
                            </form>
                        </div>
                    </div>
                    </div>
                    <div class="col-lg-4">
                    <!-- Categories widget-->
                    <br>
                    <br>
                    <div class="card mb-4">
                        <div class="card-header">AGB | Agrimensura <br>
                            <img width="60px" height="40px" src="{% static 'principal/assets/img/correo.jpg' %}">
                            <span>agrimensurabosco@gmail.com</span>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-10">
                                    <ul class="list-unstyled mb-0">
                                        <li>- Ingeniero Agrimensor</li>
                                        <li><p>Hector Bosco</p></li>
                                        <li>- Estudiante Agrimensura UBA</li>
                                        <li><p>Ezequiel Bosco</p></li>
                                        <!-- Divider-->
                                        <hr class="my-4" />
                                        <li><img width="30px" height="30px" src="{% static 'principal/assets/img/correocontacto.png' %}">Teléfono: 11 4557-1792</li>
                                        <li></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        </div>
                        <!-- Divider-->
                        <div class="card mb-4">
                            <div class="card-header">
                                Ubicacion
                                <img width="30px" height="30px" src="{% static 'principal/assets/img/ubicacion.png' %}">
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-10">
                                        <ul class="list-unstyled mb-0">
                                            <li>Trabajamos por todo Buenos Aires</li>
                                            <!-- Divider-->
                                            <hr class="my-4" />
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

principal/templates/principal/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="shortcut icon" href="{% static 'principal/assets/img/favicon.ico' %}" type="image/x-icon">
        <title>AGB | Agrimensura Bosco</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-7mQhpDl5nRA5nY9lr8F1st2NbIly/8WqhjTp+0oFxEA/QUuvlbF6M1KXezGBh3Nb" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'principal/css/style.css' %}">
    </head>
    {% block nav %}{% endblock %}
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'principal/assets/img/logo.png' %}" width="50" height=""> Agrimensura Bosco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0 navbar-nav me-auto">
                        <li class="nav-item"><a class="nav-link" href="/#nosotros">¿Quiénes somos?</a></li>
                        <li class="nav-item"><a class="nav-link" href="/#trabajos">¿Qué hacemos?</a></li>
                        <li class="nav-item"><a class="nav-link" href="/#preguntas">Preguntas frecuentes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contacto' %}">Contacto</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block contenido %}{% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="aps-group text-center">
                <div class="d-flex align-items-center justify-content-center" style="margin-bottom:10px;" data-aps-tooltip="Instagram">
                    <a class="btn-outline-dark flex-shrink-0" href="https://www.instagram.com/agrimensurabosco/" target="_blank">
                    <img src="{% static 'principal/assets/img/instagram.png' %}" style="filter: brightness(0) invert(1);" alt="Instagram"></a>
                    <a class="btn-outline-dark flex-shrink-0" href="https://api.whatsapp.com/send?phone=541145571792&text=¡Hola! Me contacto con Agrimensura Bosco porque ..." target="_blank">
                    <img src="{% static 'principal/assets/img/whatsapp.png' %}" style="filter: brightness(0) invert(1);" alt="Whatsapp"></a>
                    <br>
                    <a class="btn-outline-dark flex-shrink-0" href="https://www.linkedin.com/in/hector-bosco-338bb022/" target="_blank">
                    <img src="{% static 'principal/assets/img/linkedin.png' %}" style="filter: brightness(0) invert(1);" alt="Whatsapp"></a>
                </div>
            </div>
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Agrimensura Bosco | Web 2022 | Todos los derechos reservados</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

trabajos/templates/trabajos/amojonamiento.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Amojonamiento</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/barrio_cerrado_club.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Barrio cerrado o Club de campo</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/estado_parcelario.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Estado Parcelario</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/loteo.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Loteo</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/mensura.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Mensura</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/propiedad_horizontal.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Propiedad Horizontal</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/relevamiento.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Relevamiento</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/replanteo.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Replanteo</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/unificacion.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Unificación</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trabajos/templates/trabajos/usucapion.html
{% extends 'principal/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4" style="background-image: url('{% static 'principal/assets/img/fondo-autocad1.png' %}');">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Usucapión</h1>
            <a href="{% url 'contacto' %}"><button class="btn btn-outline-dark flex-shrink-0" type="button" href="">Solicitar Presupuesto</button></a>
        </div>
    </div>
</header>
<!-- Page content-->
<body style="background-image: url('{% static 'principal/assets/img/toposa3.jpg' %}');">
    <div class="container" >
        <div class="row">
            <h5><b>Mensura</b></h5>
            <div class="col-lg-10">
                <div class="row container">
                    <div class="col-lg-6">
                        El trabajo de mensura es
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}